### PR TITLE
convert from Adobe Illustrator to (Inkscape) SVG

### PR DESCRIPTION
**Pull request by hoijui**
reasoning:

As Adobe Illustrator is proprietary, and SVG is an open format, with at the very least Inkscape as a very good, free and open source editor, it might fit better with an open source projects community.

The conversion was done using this code:

```bash
find . -name '*.ai' \
	| while read ai
do
	svg="${ai//\.ai/.svg}"
	echo "Converting '$ai' to '$svg' (using Inkscape) ..."
	inkscape \
		--export-filename="$svg" \
		"$ai"
done
```

### CODE REVIEW

**Comment by hoijui** [comment]
My reasoning was, that SVG is a free/open format with free/open tools for editing, and it could be used as the new source file, widening the range of people that could contribute. I for example, do not have Indesign, and while I could surely get a pirated version somehow, I would rather push use Inkscape, and allow others to use it too.
To have two - technically independent - source files for the same thing, I would consider not a good idea, as then some people would work on the AI file, others on the SVG, and development would diverge, which causes gain but no gain, and confuses people. In the end, having both of them around, would mean that people need to edit both of them equally, whenever they change something, which would be counterproductive.
If you see the SVG as purely an output format though, it is a different story, but then I would rather suggest to generate the SVGs as a CI step (build-bot) here on github, and hosting them on the projects github pages, linking to them from the README maybe, instead of having them hosted in the repo directly, as that would again require people to generate and commit the SVG whenever they edit the AI files. If there is a script to generate the SVG files in the repo, then the CI job can use it, and anyone developing can run it locally too, if needed (or in their forks CI job, if they wish so).

So how I would prefer it (most desirable solution to least desirable:

1. add SVGs & remove AI files
2. keep AI files & generate SVGs in the CI job
3. keep AI files -> no change
4. add SVGs & keep AI files

what do you think/how do you see it?

**Comment by hoijui** [comment]
ouh and.. thanks for your project! :-)

We are developing standards for open source hardware documentation, and I would like to use corne as one of the sample projects for a meta-data standard we are working on, thus all the small changes. :-)

**Comment by foostan** [comment]
I understood your opinion. Thanks.
There is one big problem, I can't use inkscape and I want to manage my ai files.

I will try think about CI job for the generating SVG.

**Comment by hoijui** [comment]
oook :-)

I did it using inkscape command line, which worked fine,
but apparently the inkscape people also supply [a simple python script](
https://wiki.inkscape.org/wiki/index.php/Tools#ai2svg.py),
which depends only on python base libraries,
which should be better for a CI job.

If you decide you want this but have no time to do it, tell me, and I'll have a shot at it.

**Comment by foostan** [comment]
Close once. I agree to keep the plate data more accessible. I want to be able to automate it fully.

**Pull request closed without merging**
